spring:
  freemarker:
    requestContextAttribute: request

exp-platform:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/online
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

session:
  interval: 900

upload:
  file:
    path: /Users/xiazhiyang/Documents/java_project/cmb_online/target/classes/static/