spring:
  freemarker:
    requestContextAttribute: request

exp-platform:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/online
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

session:
  interval: 900